const express = require('express');
const bodyParser = require('body-parser');
const cors = require('cors');
const { sequelize } = require('./config/db');
require('./model/index'); 
const path = require('path');
const app = express();

const userRoutes = require('./routes/user_route');
const movieLanguageRoute = require('./routes/movie_language_route');
const adminRoute = require('./routes/admin_route');
const genreRoute = require('./routes/genre_route');
const AdminSettingRoute = require('./routes/admin_setting_route');
const MusicCategoryRoute = require('./routes/music_category_route');
const MovieCategoryRoute = require('./routes/movie_category_route');
const MovieRoute = require('./routes/movie_route');
const CastCrewRoute = require('./routes/cast_crew_route');
const MovieRatingRoute = require('./routes/movie_rating_route');
const SeriesRoute = require('./routes/series_route');
const SeasonRoute = require('./routes/season_route');
const SeasonEpisodeRoute = require('./routes/season_episode_route');
const ShortFilmRoute = require('./routes/short_film_route'); 
const ShortFilmRatingRoute = require('./routes/short_film_rating_route');
const LiveTvCategoryRoute = require('./routes/live_tv_category_route');
const LiveTvChannelRoute = require('./routes/livetv_channel_route');
const rentalRoutes = require('./routes/rental_route');
const ReportRoutes = require('./routes/report_route');
const MusicRoute = require('./routes/music_route');
const DashboardRoutes = require('./routes/dashboard_route');
const WatchlistRoutes = require('./routes/watchlist_route');
const VideoAdsRoutes = require('./routes/video_ad_route');
const MovieAdsRoutes = require('./routes/movie_ad_route');
const ShortfilmAdsRoutes = require('./routes/shortfilm_ads_route');
const SeasonEpisodeRoutes = require('./routes/season_episode_ads_route');
const LiveTvChannelAdsRoutes = require('./routes/livetv_channel_ads_route');
const SubscriptionPlanRoutes = require('./routes/subscription_plan_route');
const NotificationRoutes = require('./routes/notification_routes');
require('./cron/subscription_cron');
require('./cron/deactive_user_cron');

const baseUrl = '/api/ott';
app.use(cors());
app.use(bodyParser.json());

app.use('/uploads', express.static(path.join(__dirname, 'uploads')));

app.use(`${baseUrl}/user`,userRoutes);
app.use(`${baseUrl}/movie-language`,movieLanguageRoute);
app.use(`${baseUrl}/admin`,adminRoute);
app.use(`${baseUrl}/genre`,genreRoute);
app.use(`${baseUrl}/admin-setting`,AdminSettingRoute);
app.use(`${baseUrl}/music-category`,MusicCategoryRoute);
app.use(`${baseUrl}/music`,MusicRoute);
app.use(`${baseUrl}/movie-category`,MovieCategoryRoute);
app.use(`${baseUrl}/movie`,MovieRoute);
app.use(`${baseUrl}/movie/cast-crew`,CastCrewRoute);
app.use(`${baseUrl}/movie-rating`,MovieRatingRoute);
app.use(`${baseUrl}/series`,SeriesRoute);
app.use(`${baseUrl}/season`,SeasonRoute);
app.use(`${baseUrl}/season-episode`,SeasonEpisodeRoute);
app.use(`${baseUrl}/short-film`,ShortFilmRoute);
app.use(`${baseUrl}/short-film/rating`,ShortFilmRatingRoute);
app.use(`${baseUrl}/live-tv/category`,LiveTvCategoryRoute);
app.use(`${baseUrl}/live-tv/channel`,LiveTvChannelRoute);
app.use(`${baseUrl}/rental`, rentalRoutes);
app.use(`${baseUrl}/report`, ReportRoutes);
app.use(`${baseUrl}`, DashboardRoutes);
app.use(`${baseUrl}`, WatchlistRoutes);
app.use(`${baseUrl}/ads`, VideoAdsRoutes);
app.use(`${baseUrl}/movie-ads`, MovieAdsRoutes);
app.use(`${baseUrl}/shortfilm-ads`, ShortfilmAdsRoutes);
app.use(`${baseUrl}/season-episode-ads`, SeasonEpisodeRoutes);
app.use(`${baseUrl}/livetv_channel-ads`, LiveTvChannelAdsRoutes);
app.use(`${baseUrl}/subscription-plan`,SubscriptionPlanRoutes);
app.use(`${baseUrl}/notification`,NotificationRoutes);

const PORT = process.env.PORT || 3000;

sequelize.sync().then(() => {
    console.log('Database synced');
    app.listen(PORT, () => console.log(`Server is running on port ${PORT}`));
}).catch(err => console.error('Database connection error:', err));
